version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: laravel_postgres
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

# run:
# docker-compose -f docker-compose.dev.yml up -d --build